### ISSUE TITLE
multi-topic kafkaConsumer appears to ignore all but the first topic

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/streamsx.messaging#109]
Do we have any reason to believe that karfaConsumer works correctly when multiple topics are specified?
 
The reason why I ask is that in my Java API (streamsx.topology)) test case's use of it, I only ever see it return tuples from the first topic specified.
i.e., when the list is "testTopic1", "testTopic2",  I only see msgs from testTopic1.  reverse the order and I only see msgs from testTopic2.
 
In both cases I've manually verified that at the test's completion, both topic1 and 2 have the correctly published (produced) msgs.  the only thing that changes between runs is my switching the order of the values specified on the "topic:" param.
 
Here's the code that's being generated by the new Java API for an invocation.
Note, the properties file really is empty (issue #107).  So all of the properties that exist are shown below.
 
  ( stream<rstring topic,rstring key,rstring message> KafkaConsumer_OUT0) as KafkaConsumer = com.ibm.streamsx.messaging.kafka::KafkaConsumer()
 {
   param
     topic: "testTopic1", "testTopic2";            <==============
     propertiesFile: "etc/emptyKafkaProperties";
     threadsPerTopic: 1;
     kafkaProperty: "auto.commit.interval.ms=1000", "group.id=myKafkaStreamsTestGroup", "zookeeper.connect=localhost:2181", "zookeeper.session.timeout.ms=400", "zookeeper.sync.time.ms=200";
 }

**Comment by dlaboss** [comment]
Here's a sample SPL program that can be used to demonstrate the problem.

You need to create testTopic1 and testTopic2 - e.g., 
```
$(KAFKA_HOME)/bin/kafka-topics.sh --create --zookeeper $(ZK_STR) --replication-factor 1 --partitions 1 --topic testTopic1
$(KAFKA_HOME)/bin/kafka-topics.sh --create --zookeeper $(ZK_STR) --replication-factor 1 --partitions 1 --topic testTopic2
```

When you run the app in standalone mode (I think distributed too), expect MISSING most testTopic1 and ALL testTopic2 msgs.  Seems the same regardless of whether java7 or java8 is the standalone execution environment - see issue#117

```
namespace com.ibm.streamsx.messaging.sample.kafka;

use com.ibm.streamsx.messaging.kafka::*;

composite KafkaSampleMultiTopicConsumer {
    graph
		stream<rstring topic, rstring key, rstring message> Topic1 = Beacon() {
			param
				iterations : 10 ;
				period : 1.0 ;
			output Topic1: topic = "testTopic1", message = ctime(getTimestamp())+" testTopic1 cnt="+(rstring)IterationCount(), key = "abc";
		}
		stream<rstring topic, rstring key, rstring message> Topic2 = Beacon() {
			param
				iterations : 10 ;
				period : 1.0 ;
			output Topic2: topic = "testTopic2", message = ctime(getTimestamp())+" testTopic2 cnt="+(rstring)IterationCount(), key = "abc";
		}
		() as KafkaSink1 = KafkaProducer(Topic1) {
			param
				propertiesFile : "etc/producer.properties";
				topic : "testTopic1";
		}
		() as KafkaSink2 = KafkaProducer(Topic2) {
			param
				propertiesFile : "etc/producer.properties";
				topic : "testTopic2";
		}

	////////////////////////////////////////////////////
			
		stream<rstring topic, rstring key, rstring message> RcvdTopics = KafkaConsumer()
		{
			param
				propertiesFile : "etc/consumer.properties" ;
				topic : "testTopic1", "testTopic2" ;
		}
		() as RcvdSink = Custom(RcvdTopics as RcvdMsgs)
		{
			logic
				onTuple RcvdMsgs : println("Message: " +(rstring) RcvdMsgs) ;
		}
}
```

**Comment by Alex-Cook4** [comment]
I started debugging this and I was able to get all messages from topic1, but none from topic2. I dug deeper in the tracing. We log that a thread is started for topic1 but never for topic2 and we are getting caught in an infinite loop of these two messages (my guess is in the process of creating the topic2 thread):

25 Aug 2015 06:29:45.430 [26719] INFO #splapptrc,J[33],P[182],RcvdTopics M[Logging.scala:kafka.utils.Logging$class.info:68]  - I wrote this conflicted ephemeral node [{"version":1,"subscription":{"testTopic1":1,"testTopic2":1},"pattern":"static","timestamp":"1440497820269"}] at /consumers/mygroup/ids/mygroup_d0710b06.pok.hpc-ng.ibm.com-1440497819776-780f15e3 a while back in a different session, hence I will backoff for this node to be deleted by Zookeeper and retry

25 Aug 2015 06:29:45.832 [26719] INFO #splapptrc,J[33],P[182],RcvdTopics M[Logging.scala:kafka.utils.Logging$class.info:68]  - conflict in /consumers/mygroup/ids/mygroup_d0710b06.pok.hpc-ng.ibm.com-1440497819776-780f15e3 data: {"version":1,"subscription":{"testTopic1":1,"testTopic2":1},"pattern":"static","timestamp":"1440497820269"} stored data: {"version":1,"subscription":{"testTopic1":1,"testTopic2":1},"pattern":"static","timestamp":"1440497819924"}


This seems like it might be an issue with Kafka https://issues.apache.org/jira/browse/KAFKA-1387. Since the issue is "Kafka getting stuck creating ephemeral node it has already created when two zookeeper sessions are established in a very short period of time", it would explain why the second topic is the one we have a problem with, while the first one works fine (it never gets blocked creating an ephemeral node).  

I'm going to keep digging. I'm not positive that we should actually be writing two ephemeral nodes since they both contain "testTopic1" and "testTopic2".

**Comment by Alex-Cook4** [comment]
Figured out a fix. This line was being executed every time through the topic thread creation loop: 
Map<String, List<KafkaStream<byte[], byte[]>>> consumerMap = consumer.createMessageStreams(topicCountMap);

This leads to the infinite loop that kafka has a bug with and is redundant since it createMessageStreams(topicCountMap) creates streams for ALL the topics. Having this executed only once before the for loop fixes the issue. I have this in my forked repository (https://github.com/Alex-Cook4/streamsx.messaging) and will be merging with the IBMStreams repository soon.

**Comment by Alex-Cook4** [comment]
Fix described above was delivered.
