### ISSUE TITLE
Cannot run program spl-make-toolkit build.xml

### ISSUE THREAD

**Issue by vhl1980** [IBMStreams/streamsx.messaging#123]
My streams version is 3.2.1
I have an error in toolkit com.ibm.streamsx.messaging 0.8.1 with operator  MQTT.source.
The ouptut error :
CDIST1574E [Request Queue:] MQTT Client Error while handling MQTT client request: MqttException

(
      stream<blob data, rstring topic> MessageStream;
      stream<rstring error> ErrorStream
    ) = MQTTSource()
    {
      param
        connectionDocument : "../etc/mqtt/connections.xml";
        connection : "mqttSecurise";
        topics : "topic/#";
                topicOutAttrName : "topic";
    }

File connections.xml
<connection_specification name="mqttSecurise">
            <MQTT serverURI="myBrokerMqtt:1883" userID="user" password="password" />
</connection_specification>

When i use an other client mqtt, i don't have error.
I add more trace log in this toolkit to find error.

When i launch ant with file build.xml, i have an error 
Cannot run program spl-make-toolkit

I search this bin file spl-make-toolkit in streams studio windows, i can't find it
I use Streams studio in windows with remote workspace "LINUX"
This bin file exist in linux in $STREAMS_INSTALL/bin but not in windows.

**Comment by conglisc** [comment]
Hi vhl1980,

Can you please clarify if you trying to run ant as local ant build or remote build. The build file assumes certain environment variables are already set. 

I assumed that you are running ant by right-clicking on the build.xml file and selected run-as ant build option. If you are doing this, the ant build happens in your local windows environment.

Instead of doing this, can you run the ant command in remote terminal or run the ant build as remote build. i.e right click on the build.xml -> run as -> external tool configuration -> Remote build (create a new remote build configuration) -> Browse File System and locate ant command directory -> Select your remote toolkit directory as Working Directory.

Let me know if either of the option works for you.

Once the build works and you have generated logs, please post the logs here then we can look at your MQTTSouce issue.

Thanks,

Cong

**Comment by vhl1980** [comment]
Yes, i run ant in local with Eclipse Windows.
I try ant remote but i have error in remote shell view
/usersdev/bgd00/remote_workspace/B816673/yval12h0/experience/com.psa.streams.messaging/build.xml: line 1: syntax error near unexpected token `newline'

I don't install ant and maven in remote.
Is ant necessary ?

I change build.xml, i remove task maven.
<?xml version="1.0" encoding="UTF-8"?>

<project name="com.ibm.streamsx.messaging" basedir="." default="all">
	
	<property environment="env" />
	<property name="streams.install" value="/soft/streams321" />
	<property name="src.dir" value="impl/java/src" />
	<property name="build.dir" value="impl/java/bin" />
	<property name="impl.lib.dir" value="impl/lib" />
	<property name="lib.dir" value="lib" />
	<property name="test.run.dir" value="tests" />
	<property name="test.build.dir" value="${test.run.dir}/bin" />
	<property name="ext.downloads.dir" value="opt/downloaded" />
	<property name="gensrc.dir" value="${basedir}/impl/java/src-gen" />
	<property name="jarfile" value="com.ibm.streamsx.messaging.jar" />
	<property name="spl-mt" value="${streams.install}/bin/spl-make-toolkit" />
	
	<echo message="INIT"/>
	<target name="init">
		<mkdir dir="${build.dir}" />
		<mkdir dir="${lib.dir}" />
		<mkdir dir="${impl.lib.dir}" />
		<mkdir dir="${gensrc.dir}" />
	</target>
	
	<echo message="CLEAN"/>
	<target name="clean" depends="cpp-clean">
		<delete dir="${build.dir}" />
		<delete dir="${impl.lib.dir}" />
		<delete dir="output"/>
		<delete dir="impl/java/bin"/>
		<delete dir="${test.run.dir}"/>
		<delete dir="${test.build.dir}"/>
		<delete dir="${gensrc.dir}"/>
	</target>

	<path id="cp.streams">
		<pathelement location="${streams.install}/lib/com.ibm.streams.operator.samples.jar" />
	</path>

	<path id="cp.ext.libs">
		<fileset dir="${ext.downloads.dir}"/>
	</path>


	<path id="cp.compile">
		<path refid="cp.streams" />
		<path refid="cp.ext.libs" />
	</path>
	
	<echo message="ALL"/>
	<target name="all" depends="jar, cpp"/>
	
	<echo message="CPP"/>
	<target name="cpp">
		<exec executable="${spl-mt}" failonerror="true">
			<arg value="-i"/>
			<arg value="."/>
	    </exec>
	</target>
	
	<echo message="CPP CLEAN"/>
	<target name="cpp-clean">
		<exec executable="${spl-mt}"  failonerror="true">
			<arg value="-c"/>
			<arg value="-i"/>
			<arg value="."/>
    </exec>
	</target>

	<echo message="COMPILE"/>
	<target name="compile" depends="init, copyresources">
		<javac srcdir="${src.dir}" destdir="${build.dir}" debug="true"
			includeantruntime="no"
			excludes="com/ibm/streamsx/messaging/**/*$StreamsModel.java" source="1.6">
			<classpath>
				<path refid="cp.compile" />
			</classpath>
			<compilerarg line="-s ${gensrc.dir}"/>
		</javac>
	</target>

	<target name="jar" depends="compile">
	<jar destfile="${impl.lib.dir}/${jarfile}" basedir="${build.dir}" includes="com/ibm/streamsx/messaging/**" filesonly="true" >
		</jar>
		<delete dir="${build.dir}" />		
	</target>
	
	 <target name="copyresources">
		<copy todir="${build.dir}">
		    <fileset dir="${src.dir}" includes="**/*.xsd,**/*.properties" />
		</copy>
	  </target>	
</project>

**Comment by conglisc** [comment]
Hi Vh1980,

Yes, You need to install ant and maven in your remote system, here is the "getting started" guide

https://github.com/IBMStreams/streamsx.messaging/wiki/Getting-Started-with-Toolkit-Development

Please take a look at "
Getting Started at the Command-Line" and "
Getting Started with Streams Studio on Windows" section for details. 

In section "
Getting Started with Streams Studio on Windows", you might want to start from step 5 assuming you have imported project to studio.

For the error "line 1: syntax error near unexpected token `newline'", I think this is due to the fact that you simply run build.xml, which is not correct. Once you install ant and maven, you should revert the changes back on build.xml and change to "/usersdev/bgd00/remote_workspace/B816673/yval12h0/experience/com.psa.streams.messaging/", then issue command 

ant

that will kick off the build process.

For your info, Maven and ant are required, ant builds the projects where maven downloads the required libs for you as part of the build.

Hope this helps, 

Thanks

**Comment by vhl1980** [comment]
Hi conglisc

Okay, i'm going to install ant and maven in remote system.

Thanks you
