### ISSUE TITLE
KafkaConsumer should provide ability to read from beginning of queue at startup

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.messaging#192]
When the KafkaConsumer is started, we currently read from the last offset.  In the case when the application is shut down, and restarted, clients want the ability to start reading from the oldest offset of the topic.

There are a few ways to achieve this:
* Provide a parameter to direct the consumer to read from beginning of topic instead of the last known index
* Explore Kafka client properties to see if this can be overridden in the properties file.

I think the first option is cleaner and provide a better user experience.

**Comment by Alex-Cook4** [comment]
This can be done by setting the kafka auto.offset.reset property as described here http://kafka.apache.org/documentation.html#newconsumerconfigs. 

To make sure it works, the Kafka consumer must not use the same group.id because the offset is stored in zookeeper. Here would be the work-around. Add this to your spl in the KafkaConsumer: 
`kafkaProperty : "group.id=" +(rstring) getTimestampInSecs() ;`

So, we have a way to do it now. A parameter that takes care of this by default could be a cleaner option.

**Comment by chanskw** [comment]
Is this added in the docs?

**Comment by Alex-Cook4** [comment]
Since this is a Kafka config, along with many others, I would expect the users to read Kafka documentation: http://kafka.apache.org/documentation.html#newconsumerconfigs

We could document this relatively easily, but I think pointing users to Kafka config docs is more helpful and consistent since we're not going to document every Kafka property.

**Comment by chanskw** [comment]
If it's a common usecase, then it maybe a good idea to document and show people on how to do this.

Part of the challenge people seem to have is that the Kafka operators (or any other operators we have) hide some of the details of the  underlying technologies for the end-user.  So, it may be good to show people how this can be easily achieved, without digging into the docs.
