### ISSUE TITLE
Why is the toolkit at version 5.0?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#211]
I'm curious why the toolkit has been bumped to version 5.0?

Using semantic versioning that implies that it's incompatible with 4.0, so what features are being added that make it incompatible?

The natural next version with added functionality but remaining compatible would be 4.1

**Comment by chanskw** [comment]
Kafka operators were the reason why we had to bumped the major version.
Moving to Kafka 0.9 forced us to break compatibility as Kafka broke compatibility between 0.8 and 0.9.

**Comment by ddebrunner** [comment]
But there's a 4.0 release that supports Kafka 0.9:

https://github.com/IBMStreams/streamsx.messaging/releases/tag/v4.0.0

So if 4.0.0 (and there seem to be multiple 4.0.0 releases which is confusing) supports Kafka why is there a need to bump to 5.0?

**Comment by chanskw** [comment]
@conglisc Did you publish our branching and versioning document as we have previously discussed?

@ddebrunner, yes it is very confusing.  Problem is that we have to account for supporting for Streams 4.0 and up, as well as Streams 3.2.x.  So, we end up having a very complicated versioning scheme.  Let's wait for @conglisc to publish the document and we can further discuss.

**Comment by ddebrunner** [comment]
I see the document, but not clear why there is a bump to 5.0 from the 4.x range.

**Comment by chanskw** [comment]
@ddebrunner let me see if I can explain.  This is actually quite messy due to how big this toolkit is.

For Streams 3.2.1, we started with toolkit version v0.8.

For Streams 4.0.x, we bumped toolkit version to v2.0.0. - We bumped to 2.0 to leave more room for Streams 3.2.1 and also to account for compatibility breakage with consistent region.

For Streams 4.1.0, we bumped the toolkit version number to v3.0.0 - This is due to incompatibility added by data governance feature.  In this toolkit, we shipped a set of Kafka operators using the 0.8 version of the Kafka APIs.

After we have shipped Streams v4.1.0, the Kafka operators are enhanced to support Kafka 0.9.  This forced us to break compatibility with the Kafka operators because Kafka broke compatibility.  This change was first done in the Streams 4.0.x stream because it is where it was needed.

As a result, for Streams v.4.0 stream, we bumped the toolkit version from v2.0.0 to v4.0.0, as version 3.0.0 was already taken.

We need to forward port the same support to Streams 4.1 and add data governance support.  As a result, we went from v3.0.0 to v5.0.0 in the Streams 4.1 development stream.

**Comment by ddebrunner** [comment]
> This is due to incompatibility added by data governance feature. 

Adding new functionality typically does not break compatibility, thus maybe the major number bump could have been averted. The operator apis now contain Streams version information so it's possible that data governance could have only been enabled if Streams was at version 4.1 or higher.

The issue I'm facing is how to set a dependency on this toolkit, I can do that if it's following semantic versioning, but if adding new functionality is going to bump the major number every time then it's no longer semantic versioning and toolkits that depend on it will have to be continually updated to reflect new messaging toolkits (or have any open ended version dependency on messaging).

**Comment by chanskw** [comment]
In general, adding a new feature does not break compatibility.
However, in the case of consistent region and governance, when the feature was added, there was not a way to check for Streams version.  As a result, we had to break compatibility and force a bump in the major version number.

We are following the semantic versioning guideline.  We are not bumping the major version number for ever new feature that gets added.  We only do so when there is no way to maintain compatibility.

**Comment by ddebrunner** [comment]
Consistent region was added in 4.0 which due to application bundles was a major product change.

Data governance was added in 4.1 which also added the check version information, so it's possible it could have taken advantage of that, probably not as cleanly as just calling the methods though.

**Comment by chanskw** [comment]
@ddebrunner did we answer your question here?

**Comment by chanskw** [comment]
Closing, please reopen if you still have questions.  Thanks!
