### ISSUE TITLE
RabbitMQ support URI connection

### ISSUE THREAD

**Issue by jcschmid** [IBMStreams/streamsx.messaging#218]
Currently host and port a required for connection with RabbitMQ, connection through URI would be nice for operation in cases where host:port are not provided (Bluemix). 
Some docs:
https://www.cloudamqp.com/docs/java.html

Short version
Don't require host:port
support URI connection

**Comment by Alex-Cook4** [comment]
This would be valuable as it also provides simpler connection in many cases--user can set this single parameter instead of username, password, host, and port. This should just require a simple update to https://github.com/IBMStreams/streamsx.messaging/blob/master/com.ibm.streamsx.messaging/impl/java/src/com/ibm/streamsx/messaging/rabbitmq/RabbitBaseOper.java to: <br>
<pre>
     factory.setUri(uri);
</pre>
and ignore other parameters if uri is detected.

**Comment by Alex-Cook4** [comment]
URI support has been implemented via a URI parameter. Closing as complete.
