### ISSUE TITLE
Prune jars in downloaded.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#220]
opt/downloaded contains a number of jars that might not be needed at runtime, e.g. junit.jar.

The scala jar is another one that may not be needed and makes up a significant portion of the toollkit's size. Anyone know what it is required for?

If it's worth it maybe have Maven download the required jars into a different directory and just copy ones needed at runtime to the opt location?

**Comment by chanskw** [comment]
@Alex-Cook4 can you please take a look when you have a chance?

**Comment by Alex-Cook4** [comment]
@ddebrunner The scala jar is required for Kafka build, but I don't think it is needed at runtime. 

I can pursue pruning the JARs from a Kafka and RabbitMQ perspective. Can someone else let me know which JARs the other operators require at runtime?

**Comment by Alex-Cook4** [comment]
Removing must-fix for now. From a product perspective, this does not effect the toolkit. I have run some tests with specifying a seperate "runtime" directory that works well. 

Wouldn't it also work to just use @libraries("specific/JARs/") or at least something like "Kafka-clients-*" rather than "opt/downloaded/*"?

**Comment by Alex-Cook4** [comment]
I fixed the pom.xml to reduce the JARs downloaded. We were downloading some things that weren't needed at build or runtime. The total size now is down to 4.1 MB for all of the JARs.
