### ISSUE TITLE
KafkaConsumer start point in a consistent region?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#262]
KafkaConsumer says for a consistent region: 
_Resetting to initial state is not supported because the intial_ [sic] _offset cannot be saved and may not be present in the Kafka log. In the case of a reset to initial state after operator crash, messages will start being read from the time of reset._

I wonder if this could be handled differently if the consistent region is operator driven. 

Would it be possible to:
- Save the initial offset if one exists by making the region consistent immediately on startup
- If no initial offset exists then make the region consistent as soon as there is one, the first message?

**Comment by Alex-Cook4** [comment]
@ddebrunner I thought about that, but I don't think I was able to make it actually solve the general problem. It can help with making sure that we have a checkpoint for the rare case where we might fail before the operator is ever made consistent (if there was a huge checkpoint interval). 

It doesn't solve the case where let's say we have 10 checkpoints, and the operator tries to recover at several consistent states, before it finally gives up and goes to "resetToInitialState". In that case, the initial checkpoint isn't really helpful. It would be nice if we had a was to just save a variable so that during the reset we could pull in the offset. 

Making the region consistent as soon as possible should be an easy enhancement though.

**Comment by ddebrunner** [comment]
>  It would be nice if we had a was to just save a variable so that during the reset we could pull in the offset.

We do, an operator can save a control variable at any time.

**Comment by Alex-Cook4** [comment]
@ddebrunner I took a look at using a control variable: http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/operator/control/variable/AbstractControlVariable.html?view=kc

Warning: I have a lot of questions below...hopefully I'm not too all over the place to make sense...

Since we already have the ability to get initial offsets using `Map<Integer, Long> getOffsetPositions()` , my understanding is we could:
1. On initialization, check if that control variable already exists. 
2. If yes, seek to that offset (`void seekToPositions(Map<Integer, Long> offsetMap)`). If no, save the `Map<Integer, Long> getOffsetPositions()`  as the initial "state". 

I haven't used the abstractControlVariable interface at all. 
1. Is it practical for us to extend this interface for a Map<Integer,Long>?
2. Are there any good examples of using control variables that you know of? 
3. What if multiple Kafka operators are registering with the same "KafkaOffsets" name? Will we be protected by the non-shared option? 

I imagine the code would look something like this if we had classes/methods for Maps (sorry, I gave up actually trying to find the right methods): 


in initialize()
```
connect()
// Does this overwrite if there is already an initial value there? 
// I see there is support for "shared" across multiple operators, so how does overwriting
// get prevented if the recommended actions is 
// "If this is a shared control variable then all operators that want to access the control 
// variable create an instance of this class with the same name."
ControlVariableAccessor<Map<Integer,Long>> cntrlMap = createMapControlVariable("KafkaOffsets", false, offsetMap); 
// 1. check if that control variable already exists. Alternatively, we could use resetToInitialState to set a flag on whether we pull these initial offsets from a control variable or not. 
// 2. If yes, seek to that offset (`void seekToPositions(Map<Integer, Long> offsetMap)`). 
// If no, save the `Map<Integer, Long> getOffsetPositions()`  as the initial "state" because we are starting up for the first time. 
```

in resetToInitialState()
>Potentially use this to set a flag that we should have already saved the initial offset states (to differentiate between first-time operator initialization). 


Am I on the right track? 

Thanks for any help! I know there are a ton of questions...

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
