### ISSUE TITLE
Document details of how KafkaConsumer works in a consistent region.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#283]
The behaviour in a consistent region section never states how the operator behaves upon failure, except for the reset to initial state.

Some low level details would be useful here, e.g. documentation at the same level as the Java Kafka API.

https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html

E.g. look at the detail in sections "Controlling The Consumer's Position" and "Storing Offsets Outside Kafka".

This is needed to understand how to use these operators in applications with no data loss requirements.

Also details of how group id fits into this would be useful.

**Comment by Alex-Cook4** [comment]
I think we are currently in flux a bit in this area, but let me take an initial stab at it. 

Here is what we already have: 
>Behavior in a Consistent Region This operator can be used inside a consistent region. Operator driven and periodical checkpointing are supported. Partitions to be read from must be specified. Resetting to initial state is not supported because the intial offset cannot be saved and may not be present in the Kafka log. In the case of a reset to initial state after operator crash, messages will start being read from the time of reset.

To build off of this:
Only a single topic is supported in a consistent region, and the partitions to be consumed from must be specified. The only effect of the group.id when partition assignment is specified (as is required with consistent region) is around offset commits. If joining a group that already exists, we will start consuming at the last committed offsets (by default). In general, you will not want to join a group that has other consumers using it, since that may mean that another consumer is committing offsets for a partition that you will also start committing offsets for. The main effect of the group.id will be when a consumer initializes after a resetToInitialState it will start consuming from the last committed offset (although we are exploring ways around this in #262).  

What other details might be helpful?

**Comment by Alex-Cook4** [comment]
Thinking about this more, I think it would make sense to document a recommendation of setting  `enable.auto.commit=false` as described in the Storing Offsets Outside of Kafka section: https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html

I don't think it makes a big difference, since it doesn't show up until resetToIntialState (which is broken anyway).

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
