### ISSUE TITLE
KafkaConsumer does not guarantee at least once message processing in consistent region

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.messaging#290]
In `KafkaSource` any exception thrown during send of the records would seem to lose the records and continue processing.  E.g. at line 244 the exception is simply logged and processing continues, but at this point there is no guarantee any of the messages in `records` have been successfully processed.

An exception needs to result in the region being reset so that the messages are re-read from Kafka and submitted for processing.

**Comment by Alex-Cook4** [comment]
For this, simply calling a reset() when in a consistenRegionContext would be sufficient to solve the problem right? 

In general, we have avoided crashing at all costs in an autonomous region, but it makes sense here to not be resilient to exceptions. 

My only concern, which I think has to be ignored in this case, is: What happens if the error being caused is tuple specific? So if for some reason, there is a specific record from Kafka that causes an exception in Streams, we are going to keep replaying it and keep failing on the same tuple. I haven't seen it in the case of Kafka, but it's common in other parts of Streams that a specific tuple would cause a failure.

**Comment by schubon** [comment]
Customers are using the (from-scratch) new toolkit https://github.com/IBMStreams/streamsx.kafka that was started from scratch. If you still encounter the issue there, open an issue over there, please.
