### ISSUE TITLE
Add Consistent Region support for Kafka 

### ISSUE THREAD

**Issue by mikespicer** [IBMStreams/streamsx.messaging#98]
Kafka is a resilient feed that is a natural fit for consistent regions.  Kafka allows consumers to adjust their offset in the stream to confirm data which has been successfully processed.  This is used by other streaming systems to guarantee processing of data from Kafka and Streams should do the same.

**Comment by chanskw** [comment]
So for Kafka, KafkaProducer operator supports consistent region.  KafkaConsumer operator does not.  It is the KafkaConsumer that we need to add consistent region support for.

I looked at our current implementation of KafkaConsumer, it makes use of the high-level consumer APIs of KafkaStream, which hides a lot of details on offsets and does not allow us to reset to an older offset on demand.

For us to support consistent region, we need to revisit the KafkaConsumer operator and use the SimpleConsumer APIs.
https://cwiki.apache.org/confluence/display/KAFKA/0.8.0+SimpleConsumer+Example

The idea is that on checkpoint, we should checkpoint the current offset from the message queue.  On reset, retrieve the offset from checkpoint and reset the consumer to the saved offset.  An error case to handle is that what happens if the offset that we are trying to reset to is already discarded by the partition.  Once we have reset the offset, we can keep reading from that offset and replay messages.

@rohitsw Is this what you were referring to when you mentioned that we need to move to lower level APIs in the wiki here?
https://github.com/IBMStreams/streamsx.messaging/wiki/Consistent-Region-Support-for-Messaging-Toolkit

**Comment by Alex-Cook4** [comment]
This is actively being developed in my forked repository here: https://github.com/Alex-Cook4/streamsx.messaging

**Comment by Alex-Cook4** [comment]
This has been delivered. See behavior and architecture described here: https://github.com/IBMStreams/streamsx.messaging/wiki/Consistent-Region-Support-for-Messaging-Toolkit
